import {
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  PatientRejectSchema,
  ReferSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
} from "./schema";

export {
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  PatientRejectSchema,
  ReferSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
};
