import {
  AffiliatesSchema,
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  ForgotPassSchema,
  PatientRejectSchema,
  ReferSchema,
  ReferralSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
  VitalSignsSchema,
} from "./schema";

export {
  AffiliatesSchema,
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  ForgotPassSchema,
  PatientRejectSchema,
  ReferSchema,
  ReferralSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
  VitalSignsSchema,
};
